---
# Ansible Collections Requirements for AAP Containerized Deployment on AWS

collections:
  # AWS Collection - for EC2, VPC, security groups, etc.
  - name: amazon.aws
  - name: community.aws
  - name: ansible.posix
  - name: community.general