---
- name: Display deployment start
  hosts: localhost
  tasks:
    - name: Display deployment start
      ansible.builtin.debug:
        msg: "Starting complete AAP deployment on AWS..."

- name: Create AWS Infrastructure
  import_playbook: aws/create_infrastructure.yml

- name: Install AAP
  import_playbook: aap/install.yml
